version: "3.0"
services:
  memos:
    image: neosmemo/memos:stable
    restart: unless-stopped
    ports:
      - 5230:5230
    environment:
      - MEMOS_DRIVER=mysql
      - MEMOS_DSN=username:password@tcp(url.local:3306)/dbname
